/*
 * MainMenuState.java
 * Copyright 2012 Patrick Meade
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.rpgsheet.xcom.state;

import com.rpgsheet.xcom.render.Button;
import com.rpgsheet.xcom.service.UfoResourceService;
import com.rpgsheet.xcom.slick.Font;
import com.rpgsheet.xcom.slick.Palette;
import com.rpgsheet.xcom.render.Renderable;
import com.rpgsheet.xcom.render.Label;
import org.newdawn.slick.GameContainer;
import org.newdawn.slick.Graphics;
import org.newdawn.slick.SlickException;
import org.newdawn.slick.state.BasicGameState;
import org.newdawn.slick.state.StateBasedGame;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component("mainMenuState")
public class MainMenuState extends BasicGameState
{
    /**
     * Generated by Random.Org
     * @see http://www.random.org/cgi-bin/randbyte?nbytes=4&format=h
     */
    public static final int ID = 0x4c12d540;
    
    @Override
    public int getID() {
        return ID;
    }

    public void init(GameContainer gc, StateBasedGame sbg)
            throws SlickException
    {
        Font largeFont = ufoResourceService.getFontLarge();
        Font smallFont = ufoResourceService.getFontSmall();
        Palette mainPalette = ufoResourceService.getPaletteFull(0);
        
        languageButton = new Button(64, 90, 255, 109, mainPalette, 134, smallFont, 134, "Select Language");
        loadGameButton = new Button(64, 118, 255, 137, mainPalette, 134, smallFont, 134, "Load Saved Game");
        quitButton = new Button(64, 146, 255, 165, mainPalette, 134, smallFont, 134, "Quit");
        
        ufoTitle = new Label(largeFont, mainPalette, 139, 0, 145, 45, "UFO");
        enemyUnknownSubtitle = new Label(smallFont, mainPalette, 139, -1, 127, 61, "Enemy Unknown");
    }

    public void render(GameContainer gc, StateBasedGame sbg, Graphics g)
            throws SlickException
    {
        mainMenuWindow.render(gc,g);
        languageButton.render(gc, g);
        loadGameButton.render(gc, g);
        quitButton.render(gc, g);
        ufoTitle.render(gc, g);
        enemyUnknownSubtitle.render(gc, g);
    }

    public void update(GameContainer gc, StateBasedGame sbg, int timeDelta)
            throws SlickException
    {
        // there is nothing to update
    }
    
    private Renderable languageButton;
    private Renderable loadGameButton;
    private Renderable quitButton;
    private Renderable ufoTitle;
    private Renderable enemyUnknownSubtitle;

    @Autowired private Renderable mainMenuWindow;
    @Autowired private UfoResourceService ufoResourceService;
}
